Traceback (most recent call last):
  File "train.py", line 23, in <module>
    X = pd.read_csv(cfg.train_file_path, usecols = self.cols)
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    X = pd.read_csv(cfg.train_file_path, usecols = self.cols)
NameError: name 'self' is not defined