Val loss: 3937.5411933765076	 Val error: 189001.97752192983
Epoch - 0	 step - 1266 	Train loss - 3904.565964792879 	 MAE - 3904.5659630586524
yoooo [0.2871256  0.15180565 0.16452289 0.1445822  0.2519637 ] 4
/home/atharva1511/Downloads/CS6910/assignment2/code2/model.py:40: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y=self.soft(self.linear3(h2))
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train_one_epoch2(model, trainloader, optimizer,
  File "train.py", line 88, in train_one_epoch2
    loss = criterion(output.squeeze(), target)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: size mismatch (got input: [5], target: [1])
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train_one_epoch2(model, trainloader, optimizer,
  File "train.py", line 88, in train_one_epoch2
    loss = criterion(output.squeeze(), target)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: size mismatch (got input: [5], target: [1])